config/routes.rb
IselinApp::Application.routes.draw do
  get "home/_footer"
  get "home/contact"
  get "home/_gallery"
  get "home/about"
  get "home/_menu"
  get "home/portofolio"
  get "home/index"
  
  root :to => "home#index"
  match 'portofolio' => "home#portofolio"
  match 'about' => "home#about"
  match 'contact' => "home#contact"
  match 'gallery' => "home#_gallery"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def about
    
  end
  
  def index
    @images = Dir['app/assets/images/frontpage_slideshow/*.*'].map {|f| f.sub('app/assets/images/','') }
    
  end
  
  def _menu
    
  end
  
  def portofolio
    @images = Dir['app/assets/images/frontpage_slideshow/*.*'].map {|f| f.sub('app/assets/images/','') }
    
    @gallery = Dir['app/assets/images/gallery/*'].map
        
  end
  
  def _gallery
    path = params[:path]
    @images = Dir[path.to_s+'/*.*'].map {|f| f.sub('app/assets/images/','') }
    @thumbnails = Dir[path.to_s+'/thumbnails/*.*'].map {|f| f.sub('app/assets/images/','') }
  end
  
end

app/helpers/application_helper.rb
require 'rubygems'
require 'RMagick'

module ApplicationHelper
  
  def getHeight(picture)
  
    image = Magick::Image.read('app/assets/images/'+picture).first

    return image.rows
  
  end
  
  def getWidth(picture)
  
    image = Magick::Image.read('app/assets/images/'+picture).first

    return image.columns
  
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
  
end

app/views/home/_footer.html.erb
Mail: <%= image_tag("email_adress.png", :alt => "email", :align => "top") %>
<br>
Phone: +47 48 06 10 56 
<br>
© 2012 Iselin Jansen Photography. All rights reserved.

app/views/home/_gallery.html.erb
<script type="text/javascript">
$(function(){
	$("#gallery").slides({
		effect: 'fade',
		container: 'gallery_container',
		play: 5000,
		pause: 2500,
		hoverPause: true
	});
});
$(document).ready(function(){
	function closeWindow(){
		$(parent.document).find('#mask, .window').hide();
		$(parent.document).find('.galleryIframe').attr('src', "");
		$(parent.document).find('.galleryIframe').empty();
	}
	
	$(document).keyup(function(e){
		switch(e.which){
			case 27:
	       		closeWindow();
	       		break;
		}
	});
	var windowWidth = $(window).width();
	var windowHeight = $(window).height();
	
	//setup of pagination
	$('.pagination').wrap('<div class="scrollPageination" />');
	$('.scrollPageination').css('width', windowWidth);
	$('.scrollPageination').css('margin-left', -((windowWidth-$('.gallery_container').width())/2).toFixed(0)-1);

	var squareSide = windowHeight-($('.gallery_container').height() + parseInt($('#gallery').css('margin-top'), 10) + parseInt($('.pagination').css('margin-top'), 10)*2);
	var numberOfChildren = $('.pagination').children().length;
	
	$('.pagination li').css('width', squareSide);
	$('.pagination li').css('height', squareSide);
	if (isNaN((squareSide + parseInt($('.pagination li').css('margin'), 10) + 2) * numberOfChildren)){
		$('.pagination').css('width', (squareSide + 1 + 2) * numberOfChildren);
	} else {
		$('.pagination').css('width', (squareSide + parseInt($('.pagination li').css('margin'), 10) + 2) * numberOfChildren);
	}
	
	//replacing pictures in pagination
	$('.pagination li').each(function(e){
		var listElement = $(this);
		var thumbnail = $('.thumbnails').children().first();
		listElement.find('a:first').contents().replaceWith(thumbnail);
	});
	
});
</script>
<div id="gallerywrapper">
	<div id="windowFrame">
		<div id="gallery">
			<div class="gallery_container">
				<% @images.sort.each do |image|%>
					<% if image.exclude?("forside_") && image.exclude?("thumbnails") %>
						<div>
							<%= image_tag(image, :alt => "image", :style => "margin-top:"+((420 - getHeight(image))/2).to_s+"px;" + "margin-left: "+ ((595-getWidth(image))/2).to_s + "px") %>
						</div>		
					<% end %>
				<% end %>
			</div>
			<a href="#" class="prev"><%= image_tag("arrow-prev.png", :alt => "Arrow Prev", :width => "24", :height => "43") %></a>
			<a href="#" class="next"><%= image_tag("arrow-next.png", :alt => "Arrow Next", :width => "24", :height => "43") %></a>
		</div>
	</div>
</div>
<div class="thumbnails" style="display: none">
	<% @thumbnails.sort.each do |thumbnail|%>
		<%= image_tag(thumbnail, :alt => "thumbnail", :style => "padding-top:"+((61 - getHeight(thumbnail))/2).to_s+"px;" + "padding-left: "+ ((57-getWidth(thumbnail))/2).to_s + "px") %>
	<% end %>
</div>

app/views/home/_menu.html.erb
<div id="header">
	<%= image_tag("header.jpg", :alt => "Header") %>
</div>
<script>
$(document).ready(function(){
	
	var top = $('#menu').offset().top;
	
	$(window).scroll(function (){
		var y = $(window).scrollTop();
		
		if(y >= top) {
			$('#menu').addClass('fixed');
			$('#menuWrapper').css('top', '0px');
		}else{
			$('#menu').removeClass('fixed');
			$('#menuWrapper').css('top', '374px');
		}
	});
});
</script>
<div id="menuWrapper">
	<div id="menu">
		<nav>
			<ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Portofolio", portofolio_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
			</ul>
		</nav>
	</div>
</div>

app/views/home/about.html.erb
<div id="page">
	<div id="elementWrapper">
		<%= render "menu" %>
		<div id="content">
			<div id="contentwrapper">
				<%= image_tag("about_me/aboutme.jpg", :alt => "AboutMe", :id => "aboutpicture") %>
				<h1>Iselin Jansen</h1>
				<p>
					Iselin Jansen (1991) comes from Fetsund, a small town just outside Oslo. 
					She’s been dancing since she was three years old, but discovered early her passion for photography. 
					At high school she studied classical ballet, contemporary and jazz.
				</p>
				<p>
					From 2010 til 2012 she studied photography at Bilder nordic school of photography. 
					Here she had teachers and mentors as Isidor Åstrøm, Margaret M. De Lange, 
					Marcus Bleasdale, Damian Heinisch, Hans Olav Forsang, Amber Terranova and Ashley Cameron among others. 
				</p>
				<p>
					As a natural choice Iselin photographs a lot of dancers and she has worked with the choreography duo Subjazz, 
					ODE (Oslo danse ensemble), dancers from the norwegian national ballet, and a lot of professional freelance dancers. 
					She has also worked with different music and media productions. 
					Basicly Iselin photographs dance, fashion and streetlife. 
					She mixes her love of theatre with street photography.
				</p>
			</div>
		</div>
	</div>
	<div id="footer"><%= render "footer" %></div>
</div>

app/views/home/contact.html.erb
<div id="page">
	<div id="elementWrapper">
		<%= render "menu" %>
		<div id="content">
			<div id="contentwrapper">
				<%= image_tag("contact/contact.jpg", :alt => "Contact", :id => "contactpicture") %>
				<h1>Contact</h1>
				<p>
					Mail: <%= image_tag("email_adress.png", :alt => "email", :align => "top") %>
				</p>
				<p>
					Phone: +47 48 06 10 56 
				</p>
				<p>
					<a href="https://twitter.com/iselinjansen" id="twitterBadge" class="twitter-follow-button" data-show-count="false">Follow @iselinjansen</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
					<br/>
					<a target="_blank" href="http://tumblr.com/follow/iselinjansen" onclick="javascript:_gaq.push(['_trackEvent','outbound-article','http://tumblr.com']);"><img src="http://i1076.photobucket.com/albums/w458/mrtumblring/Button4-7.png" id="tumblrBadge" title="Tumblr Follow Me" border="0" /></a><br />
					<br/>
				</p>
				<script>
				$('#tumblrBadge').css('width', '138px');
				$('#tumblrBadge').css('margin-left', '-2px');
				</script>
			</div>
		</div>
	</div>
	<div id="footer"><%= render "footer" %></div>
</div>

app/views/home/index.html.erb
<div id="page">
	<%= render "menu" %>
	<div id="elementWrapper">
		<div id="content">
			<div id="contentwrapper">
				<script type="text/javascript">
				$(function(){
					$("#slides").slides({
						effect: 'fade',
						generatePagination: false,
						generateNextPrev: false,
						play: 5000
					});
				});
				</script>
				<div id="slidewrapper">
					<div id="frame">
						<div id="slides">
							<div class="slides_container">
								<% @images.each do |image|%>
								<div>
									<%= image_tag(image, :alt => "image", :style => "margin-top:"+(250 - (getHeight(image)/2)).to_s+"px") %>
								</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="footer"><%= render "footer" %></div>
</div>

app/views/home/portofolio.html.erb
<script>
 
$(document).ready(function() {  

 	function closeWindow(){
		$('#mask, .window').hide();
		$('.galleryIframe').attr('src', "");
		$('.galleryIframe').empty();
	}
	
	function setFocusThickboxIframe() {
	    var iframe = $(".galleryIframe")[0];
	    iframe.contentWindow.focus();
	}

    //select all the a tag with name equal to modal
    $('a[name=modal]').click(function(e) {
		
		var gallery_url = $(this).attr('id');
		$('.galleryIframe').attr('src', "<%= url_for 'gallery' %>" + "?path=" + gallery_url);
		
        //Cancel the link behavior
        e.preventDefault();
        //Get the A tag
        var id = $(this).attr('href');
     
        //Get the screen height and width
        var maskHeight = $(document).height();
        var maskWidth = $(window).width();
     
        //Set height and width to mask to fill up the whole screen
        $('#mask').css({'width':maskWidth,'height':maskHeight});
         
        //transition effect     
        $('#mask').fadeTo("slow",0.9);
        $('#mask').fadeIn(1000);      
     
        //Get the window height and width
        var winH = $(window).height();
        var winW = $(window).width();
      
        //Set the popup window to center
        $(id).css('top',  winH/2-$('#frame').height()/2);
        $(id).css('left', winW/2-$('#frame').width()/2);
     
        //transition effect
        $(id).fadeIn(1000); 

		//focus on iframe for key-events to work
		setTimeout(setFocusThickboxIframe, 100);
     
    });
     
    //if close button is clicked
    $('.window .close').click(function (e) {
        //Cancel the link behavior
        e.preventDefault();
		closeWindow();
    });     
     
    //if mask is clicked
    $('#mask').click(function () {
        closeWindow();
    });
	
	$(document).keyup(function(e){
		switch(e.which){
			case 27:
	        	closeWindow();
	        	break;
		}
	});
     
});
</script>
<div id="boxes">
    <div id="dialog" class="window">
		<div style="float: right; padding: 5px; left: 755px; z-index: 10000; position: absolute;">
			<a href="#" class="close">Close</a>
		</div>
		<iframe id="frame" name="galleryPopupIframe" style="z-index: 9999" frameborder="0" scrolling="no" class="galleryIframe" wmode="Opaque" src="">
		</iframe>
    </div>
    <div id="mask"></div>
</div>
<div id="page">
	<%= render "menu" %>
	<div id="elementWrapper">
		<div id="galContent">
			<div id="contentwrapper">		
				<div id="gallerywrapper">
					<div id="galFrame">
						<table id="gallery_table">
							<tr>
							<% col = 0 %>
							<% rows = 1 %>
							<% @gallery.sort.each do |folder|%>
								<td><a href="#dialog" name="modal" id="<%= folder %>" style="text-decoration: none">
								<% galImg = nil %>
								<% galImgFolder = Dir[folder+"/*"].map %>
								<% galImgFolder.each do |file|%>
									<% if file.include?("forside_") %>
										<% galImg = file %>		
									<% end %>
								<% end %>
								<%= image_tag(galImg.sub('app/assets/images/',''), :alt => "image") %>
								</a>
								<br>
								<a href="#dialog" id="<%= folder %>" name="modal">
								<%= folder.sub('app/assets/images/gallery/','').to_s.strip %>
								</a></td>
								<% if col == 1 %>
									<% col = 0 %>
									<% rows = rows + 1 %>
									</tr>
									<tr>
								<% else %>
									<% col = col + 1 %>
								<% end %>
							<% end %>
							<script> 
								$('#galFrame').css('height', '<%= rows.to_s %>' * 330 + "px");
								$('#galContent').css('height', ('<%= rows.to_s %>' * 330)+30 + "px");
							</script>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="footer"><%= render "footer" %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iselin Jansen Photography</title>
  <!-- Page created and designed by Nikolas Jansen. -->
  <!-- Contact: nikolas.jansen [at] gmail.com -->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>